### ISSUE TITLE
Include instructions to build from source

### ISSUE THREAD

**Issue by mchubby** [fanf2/regpg#1]
Hello Tony,

Would you please include instructions to build from source?

* perl version requirements (if any)
* required Perl modules (e.g. for Debian and Ubuntu distributions, required packages are make and libtext-markdown-perl, cpan instructions etc.)
* Type `make` to build everything, `make regpg` for just the program,  `make test` to run the testsuite, `make install` to install into ${HOME}/bin etc.

**Comment by fanf2** [comment]
Good suggestion, thanks!

I've put most of the details in `doc/contributing.md` and I've improved the relevant sections in the README.

Let me know if I have missed anything!

**Comment by fanf2** [comment]
A followup note just to say I cut a regpg-0.100 release - thanks for your help!

**Comment by mchubby** [comment]
You're welcome! Thanks for the followup, and cheers for the milestone release!
