### ISSUE TITLE
Tests fail when locale is not set to C or English

### ISSUE THREAD

**Issue by mchubby** [fanf2/regpg#2]
### Tests fail when locale is not set to C or an English one ###

***Steps to reproduce***:
``$ make && make test``

***Expected***:

All perl tests succeed.

***Observed***:

Some tests fail because gpg's output do not match expected patterns (e.g. `('?^:imported)`

***Workaround***:
``$ LANG=C make test``

**Comment by fanf2** [comment]
Another very good catch, thanks!

I have pushed a fix
