### ISSUE TITLE
`regpg init git` should work when user has no secret key

### ISSUE THREAD

**Issue by mcv21** [fanf2/regpg#6]
Hi,

One might reasonably want to run `regpg init git` without having a secret key available (e.g. to arrange such that you can use `git diff` on the keyring and have it show you changes usefully). This doesn't currently work:

```
$ regpg init git
pipe from gpg --list-secret-keys --with-colons git
gpg: error reading key: secret key not available
pipe from gpg failed
```

Thanks,
Matthew

**Comment by fanf2** [comment]
This should only happen if there is no `pubring.gpg`, which will only occur if `regpg` isn't set up in this project at all. The idea is that you'll be setting up `regpg` on your dev workstation where you have keys available; once it is set up, `regpg init git` will fix up the `git` config for fresh clones without needing private keys.

The other situation where this might occur is if your cwd doesn't contain the project's `pubring.gpg`, in which case you need a `cd` or a `-k` option.

Does that make sense?

**Comment by mcv21** [comment]
Ah, yes, I see. Sorry for the noise.
